# Generated by Django 3.1.1 on 2020-10-15 16:22

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20201015_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='USD', max_digits=19, validators=[djmoney.models.validators.BaseMoneyValidator]),
        ),
    ]
