# Generated by Django 3.1.1 on 2020-10-15 18:04

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20201015_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=djmoney.models.fields.CurrencyField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
    ]
