# Generated by Django 3.1.1 on 2020-10-15 18:13

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_auto_20201015_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='USD', max_digits=19),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
