# Generated by Django 3.1.1 on 2020-10-15 19:33

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_auto_20201015_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=19),
        ),
    ]
