# Generated by Django 3.1.1 on 2020-10-16 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_auto_20201015_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['source']},
        ),
    ]
