# Generated by Django 4.2.1 on 2023-05-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_alter_category_id_alter_expense_id_alter_income_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='discretionary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='reimbursable',
            field=models.BooleanField(default=False),
        ),
    ]
