# Generated by Django 4.2.1 on 2023-05-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_expense_discretionary_expense_reimbursable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='discretionary',
            field=models.BooleanField(default=True),
        ),
    ]
