# Generated by Django 4.2.1 on 2023-05-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_alter_expense_discretionary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='discretionary',
            new_name='budgeted',
        ),
    ]
